# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# disable building until xcode 9 image is out.
branches:
  except:
  - swift-4

language: objective-c
osx_image: xcode8
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail
- travis_retry xcodebuild test -project Formulitic.xcodeproj -scheme Formulitic_iOS -destination 'platform=iOS Simulator,name=iPhone 7' ONLY_ACTIVE_ARCH=NO | xcpretty
- travis_retry pod lib lint --allow-warnings
